packages/ui/Input/index.tsx

- improvements discussed on slack
- accessibility of error messages, 
- prevent form submitting on icon button click
- reserve additional space for supporting label so that inputs does not shift when stacked in the form
- slight animation delay was added to eliminate label jumping when the user clicks on the icon button while the password input is empty ⬇️ 
https://user-images.githubusercontent.com/80450315/229596033-6d96daaf-4a6b-4c9e-9882-996c60971f54.mp4

refactor: input component improvements #P23-200

---

apps/web/app/(regflow)/sign-up/EmailScreen.tsx
apps/web/app/(regflow)/sign-up/page.tsx
apps/web/lib/dictionary.tsx

- task: https://tracker.intive.com/jira/browse/PATRO23-207
- preview: https://patronage2023-js-web-git-feature-p23-207-sign-61dbe2-wlechowicz.vercel.app/sign-up
To discuss - position of text element with link ( `<FooterStyled>`) - right now it is positioned in the same distance from the button as on the design. Implementation has less elements than design, so this text looks kinda strange in this position ;-) maybe it should be closer to the button or more at the bottom of the card?

feat: sign up - step1 - email screen #P23-207

---

apps/web/app/(regflow)/layout.styles.tsx
apps/web/app/(regflow)/sign-up/SuccessErrorScreen.tsx
apps/web/lib/dictionary.tsx
package-lock.json
packages/ui/Button/index.tsx
packages/ui/Icon/index.tsx
packages/ui/Link/index.tsx
packages/ui/index.tsx
packages/ui/theme.tsx

- Ticket: https://tracker.intive.com/jira/browse/PATRO23-210
- [Success Preview](https://patronage2023-js-web-git-feature-p23-210-step-f918d5-wlechowicz.vercel.app/sign-up)
- [Error Preview](https://patronage2023-js-web-git-feature-p23-210-step-f918d5-wlechowicz.vercel.app/sign-up/error)
Task: Prepare (4/4) screen for ```FlowController```.
```SuccessErrorScreen``` receives three types of props:
- ```success```: status of validation (```boolean```)
- ```onBackToStart```: function that takes the user back to the first screen in the registration process
- ```loginHref```: if the ```success``` status is true, the button on the screen will become a link with a href property equal to  ```loginHref```
in code:
```javascript 
<SuccessErrorScreen success={false} onBackToStart={onBackToStart} …
```

feat: sign up success-error screen #P23-210

---

packages/ui/Logo/index.tsx

Task: https://tracker.intive.com/jira/browse/PATRO23-251
- wrapper was changed from `div` to `a` and a `href` was added
- child element was changed to be an inline element like the parent ( from `div` to `span`)
- additionally, unnecessary exports were removed

refactor: add link to logo #P23-251

---

apps/storybook/stories/CurrencySelector.stories.tsx
packages/ui/CurrencySelect/CurrencySelect.styled.tsx
packages/ui/CurrencySelect/index.tsx

Hello! This is PR of my task [Fix Currency Selector styles in storybook](https://tracker.intive.com/jira/browse/PATRO23-267).
I think now it looks like in web and looks more like in design (I deleted borders on focus). 
[Check WEB](https://patronage2023-js-dbqlopdja-wlechowicz.vercel.app/)
Budgets > Add new budget > Currency
[Check Storybook](https://patronage2023-js-storybook-jyppd9mtk-wlechowicz.vercel.app/?path=/story/currency-select--select)
Have a nice day! 😃

fix: currency selector styles in storybook #P23-267 

---

apps/web/app/(navigation)/budgets/[id]/TransactionsTable.styled.tsx
apps/web/app/(navigation)/budgets/[id]/TransactionsTable.tsx
packages/ui/TransactionDropdownMenu/index.tsx

task: https://tracker.intive.com/jira/browse/PATRO23-282
- **column sizes are set as %** - there is a difference in columns' width when you compare it to the design. This is due to the fact, that it has to display well on a variety of screen sizes. Setting it to widths similar to the ones on the design would always produce some problems on different widths, especially around breakpoints. I tried to find the best widths that work well on a bigger screen, around 1025px, and down to 768px. Below that we would need additional design and probably some columns should be hidden then.
- **other differences compared to design:**
- as we discussed, the "Creator" column (header and contents) is centered (it is to the left in the design)
- I centered also the "Amount" header (which seems to be to the …

fix: transactions table #P23-282

---

apps/web/lib/category-map.ts
apps/web/lib/types.ts
packages/ui/CategoryIcon/index.tsx
packages/ui/theme.tsx

task: https://tracker.intive.com/jira/browse/PATRO23-287
- `categoryMap` maps category names accepted by the backend to an object of type:
```
export type CategoryType = {
name: string;
icon: {
name: string;
foreground: string;
background: string;
};
};
```
- the same type is used by `CategoryIcon` component
- missing colors were added to the theme

feat: category map #P23-287

---

apps/storybook/.storybook/preview-head.html

Adding font weight (400) opion to Signika font in storybook:
Before:
`<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Signika:wght@600&display=swap" />`
After
`<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Signika:wght@400;600&display=swap" />`

fix: adding 400 weight option to Signika font in storybook preview-head

---

apps/storybook/stories/FormFooter.stories.tsx
apps/web/app/(regflow)/sign-in/page.tsx
apps/web/app/(regflow)/sign-up/EmailScreen.tsx
apps/web/lib/dictionary.tsx
packages/ui/FormFooter/index.tsx
packages/ui/index.tsx
packages/ui/theme.tsx

ticket: https://tracker.intive.com/jira/browse/PATRO23-304
- add missing text with link in log-in form to be able to move to sign-up page ➡️ 
- dictionnary has been updated! 📖 
Element that was missing: 
<h2>Update 📣 </h2>
Due to acheive proper styles from design and avoid code repetition,  component `<FormFooter>` has been created. It receives props such as: 
```typescript
type FormFooterProps = {
basicText: string;
linkText: string;
href:string;
};
```  
In connection with this change, component was added to Storybook as well  📖

fix: add missing link in login form #P23-304

---

apps/web/app/(navigation)/(singleCard)/MainPageTranslated.tsx
apps/web/pages/api/auth/[...nextauth].ts

Small middleware fix which removes custom encoding method of JWT token - token is encoded by default.
Small landing page refactor with changing button based on the logged user informations.
I've kept the unnecessary data on the frontpage for now as an example on how to use useSession hook.

fix: next-auth middleware fix and main page refactor#P23-196

---

apps/storybook/stories/TrendChip.stories.tsx
apps/web/lib/dictionary.tsx
packages/ui/FormFooter/index.tsx
packages/ui/Icon/index.tsx
packages/ui/TrendChip/index.tsx
packages/ui/index.tsx
packages/ui/theme.tsx

ticket: https://tracker.intive.com/jira/browse/PATRO23-309
<h3>Overview 👀 </h3>
Trend chip component that accepts value in props. Depending on a positive or negative value, it takes proper color and icon.
<h4>Update! 💥  </h4> Component takes as well `ariaLabel` prop.
```typescript
export type TrendChipProps = {
value: number;
ariaLabel: string;
} & React.HTMLProps<HTMLDivElement>;
```  
<h2> Update: problem resolved ✔️ </h2>
<h3>Problem 🤔</h3>
I tried to imagine a situation where user can get really high income, and then value could be quite long. In that situation, even though TrendChip doesn't have width, but only paddings, the value goes beyond it's border. Now this problem is caused by wrapper in storybook, so the width depends on parent element. Should it be that way, or maybe we …

feat: trend chip #P23-309

---

packages/ui/Input/index.tsx

In forms, clicking enter triggers a button, which is used to trigger submit.
In our case, the icons inside the inputs are buttons, so clicking enter would trigger the first button in the queue (1. Clear input button, 2. Show/hide password button, 3. Submit button). If we remove the clear function, the next button is triggered.
```tsx
<button type="button">Show</button>
```
Setting `type="button"` in buttons makes them ignored when enter is clicked.

fix: email resets after pressing enter in form #P23-368

---

apps/web/app/(regflow)/sign-in/page.tsx

Tiny fix for the situation when you type in the wrong credentials and the error does not display, instead, the page reloads.
I don't know why this got removed in some previous PR:
`redirect: false,`

fix: credentials error #P23-376

---

apps/web/app/(navigation)/SideNavigationBar.tsx
packages/ui/SideNavigationBar/SubMenu/index.tsx
packages/ui/SideNavigationBar/index.tsx

Task [Fix Budget List Search](https://tracker.intive.com/jira/browse/PATRO23-375)
1. Now when you type something in search bar and change tab (e.g. Reports) and open Budgets again, search bar will be empty and budget list will show all budgets.
2. When you go to specyfic budget after search and then open again budget list, search bar again will be empty and budget list will show all budgets.
Thanks to @Noshi96 for a hint how to fix it in a comment on Slack :)

fix: budget list search #P23-375

---

apps/web/app/(regflow)/sign-in/page.tsx
apps/web/middleware.ts
packages/ui/Button/index.tsx

task: https://tracker.intive.com/jira/browse/PATRO23-387
- user should be now redirected correctly after pressing the "sign in" button
It looks like on production build after login, Next Router needs to be refreshed to access routes to which user previously had no access (`/`) (route `/` was recently changed to be protected).
To reproduce this error locally, you have to run production build locally:
- go to `apps/web` folder in terminal and 
- run commands `npm run build` then `npm run start`
- if user would logout while being on one of the "settings" subpages, then they would end up not on login page but on "settings" page, but without the side nav bar
- login form was sending request twice, since the button is of `type="submit"` and had also `onClick={submit}`

fix: no redirect on sign in #P23-387

---

apps/web/app/(navigation)/budgets/[id]/BudgetDetails/BudgetStatistics.tsx

Fixed logic for range calculation, the bug was happening when we were looking at older budgets 🚀 
Edit: also since we are able to create transaction in the future i changed how how week and month are calculated

fix: now should properly calculate range

---

apps/web/components/SideNavigationBar/index.tsx
packages/ui/NavList/index.tsx

<h2> Quick improvement for removing duplicates from budget's list 🏃 </h2>
As @wlechowicz suggested: 
- Logic of removeDuplicates function has been changed 
- Bug with adding lastBudgetRef has been fixed  
> This is a bug that's been sitting here for a while, might as well fix it now. This adds last budget ref to every single budget on the list, instead of the last one.

refactor: fix adding lastBudgetRef, refactor removeDuplicates function #P23-396

---

apps/web/app/(navigation)/budgets/[id]/BudgetDetails/TrendChart.tsx

Small fix that removes: Error: <svg> attribute height: Expected length, "auto" for placeholder trendchart

fix: svg "auto" error fix#P23-399

---

apps/web/app/(navigation)/budgets/[id]/BudgetContent/CreateNewBudget.tsx
apps/web/app/(navigation)/budgets/[id]/TransactionTableController/TransactionsTable.tsx
apps/web/app/(navigation)/budgets/[id]/TransactionTableController/index.tsx

I added a mapping of our columns from the transaction table to the column names BE requires in SortDescriptor. This allowed to combine @mpiwonski previous work with the current version of the BE endpoint.

refactor: sorting transactions by column - BE integration #P23-403

---

apps/web/app/(navigation)/budgets/[id]/TransactionTableController/TransactionsTable.tsx
apps/web/app/(navigation)/budgets/[id]/TransactionTableController/index.tsx
apps/web/lib/types/index.ts

The creator's avatar displayed in the transaction table has been changed, now it is the user's avatar returned by BE. If the transaction does not have an assigned user, no avatar is displayed (this applies to old transactions).
There is an error on smutna 🐸  and even for new transactions a user is not added (BE checks why), for 2 other users for whom I checked for new transactions, users are added and they are correctly displayed in the table.
I also added a Personal Card to the avatar in the table

refactor: creator avatar in transaction table #P23-405

---

apps/web/components/SideNavigationBar/index.tsx
packages/ui/ExportDropdown/index.tsx
packages/ui/SideNavigationBar/SubMenu/SubMenu.styled.tsx
packages/ui/SideNavigationBar/SubMenu/index.tsx

Ticket: https://tracker.intive.com/jira/browse/PATRO23-361
By selecting send by email from the export dropdown option, we can export our budgets. After a successful operation, the budgets as a CSV file will be sent to our email address, and we will see a success toast.

feat: export budgets via mail #P23-361
